import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { MovieProvider } from "../context/useMovie";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <div className="min-h-screen flex flex-col text-white blur-cover font-sans backdrop-blur-sm" style={{
                  backgroundImage: "url('/images/bg4.jpg')",
                  objectFit: "cover"
            }}>
        <Navbar />
        <MovieProvider>
        {children}
        </MovieProvider>
        <Footer />
</div>
      </body>
    </html>
  );
}
